### PR TITLE
Apply new rules for signatures and witness events

### PR DESCRIPTION
**Pull request by it-spiderman**
https://github.com/inblockio/mediawiki-extensions-Aqua/issues/397

### CODE REVIEW

**Comment by it-spiderman** [comment]
now that signature is stored on the revision that injects it (not on the one that was current at the time of signing), verification though external verifier fails.
This is becuase when you sign, messages is `i sign .... {verification_hash of current revision}`, and that is used for verification. But that hash specified in message does not match the revision that holds the signature (as it is now added to the revision after it, one that injects the sig)

Also, Verifier is freaking out in general

**Comment by FantasticoFox** [comment]
We will have a look today and test. Will get back with any feedback I have.

Thank you Dejan!

**Comment by FantasticoFox** [comment]
Find an example JSON page. The Witness object exists but the path with the merkle-tree-path is completly missing. Without it, it will not work.

Furthermore it does not inject the witness event in the page itself and does not create a new revision.
Please provide a new commit with fixes for this.

[6c3fbf41e5_Testing_Signatures.json](https://github.com/user-attachments/files/15991515/6c3fbf41e5_Testing_Signatures.json)

**Comment by it-spiderman** [comment]
Updated commit, hopefully all is good now

**Comment by FantasticoFox** [comment]
Signature is tested and works. Verifier needs adjustment. 
Manuel tests for signature checks out after putting the signature to its original position.
[cf4f30f866_Whatever_Page.json](https://github.com/user-attachments/files/16039546/cf4f30f866_Whatever_Page.json)

**Comment by FantasticoFox** [comment]
Witness data is malformatted and at the wrong place for verifier to process.

[cf4f30f866_Interactive_Tutorial.json](https://github.com/user-attachments/files/16039564/cf4f30f866_Interactive_Tutorial.json)

"structured_merkle_proof": [] is still empty in the second revision and is now populated at the wrong position witness_slot in content. The structured merkle proof needs to be stored as JSON in the witness object outside of the content.

The witness-slot does contain now all verification data (including merkle-tree-proof). Its redudent to the witness data in the JSON and not required in full length in there as it is invisibile to the user anyway at this moment.
A useful information at this place would be to show the link to the onchain timestamp event with basic witness information.

**Comment by FantasticoFox** [comment]
Like the Signature field:

image

The Witness field should include useful user information about the witness event.

Those information are:

- Witness Netzwerk (e.g. Mainnet, Sepolia, Holesky)
- Link so Etherscan (Witness_event_transaction_hash) clickable, transaction hash needs to be visible for potential manuel lookup
- Link to Witness event (the page which is visible in the publisher)

Successcreteria: 
- Please test that the verifier is getting green with signature and witness event being manuelly moved into the revision before for testing purpose.

**Pull request merged**
