### PR TITLE
fix: Do not fatal when verificaiton data for transclusion does not exist

### PR DESCRIPTION
**Pull request by it-spiderman**
Fixes https://github.com/inblockio/mediawiki-extensions-Aqua/issues/307

### CODE REVIEW

**Comment by FantasticoFox** [comment]
image

Behavior is in my testing as expected.

**Comment by FantasticoFox** [comment]
Futher testing, same positive result. Fatal error is gone, works fine.

image

**Review by FantasticoFox — APPROVED** [review]
Tested it, works as expected. Well done.

**Comment by rht** [comment]
I'd say the text should have been "invalid hash or missing verification data", for consistency.

**Comment by rht** [comment]
Reminder to rebase.

**Comment by it-spiderman** [comment]
> I'd say the text should have been "invalid hash or missing verification data", for consistency.

ok, but i would do it in a separate commit, since text was not added in this PR

**Pull request merged**
