### PR TITLE
Upgrade to MW 1.39

### PR DESCRIPTION
**Pull request by it-spiderman**

### CODE REVIEW

**Comment by it-spiderman** [comment]
Commits should be squashed, so that it appears as a single change

**Comment by rht** [comment]
@it-spiderman should I wait until you have fixed the CI fails?

**Comment by rht** [comment]
Is it a deep error, or shallow error that can be iteratively fixed quickly?

**Comment by it-spiderman** [comment]
Hello @rht Main CI issue is that it not building MW 1.39 and its still using composer 1. TBH, i dont know how to change the CI setup. Can you help here?

**Comment by rht** [comment]
This code snippet needs to be modernized: https://github.com/inblockio/mediawiki-extensions-Aqua/blob/3cef7b5f57296de683f074ae1b968e31e7ec6d79/.github/workflows/ci.yml#L35-L40.

**Comment by it-spiderman** [comment]
thank you @rht , i did it in https://github.com/inblockio/mediawiki-extensions-Aqua/commit/8afe38dfe37dc1d79e476ce5a211385a3bd935a8
However, i dont know how to upgrade composer to V2

**Comment by rht** [comment]
If you don't pin the composer version (e.g. https://github.com/ProfessionalWiki/WikibaseExport/blob/773c22ce26bf756274fbcaf3acc2d1090d84030c/.github/workflows/ci.yml#L33-L39), it might work.

According to https://github.com/shivammathur/setup-php, you could even force it to be v2:
```
- name: Setup PHP with composer v2
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.2'
    tools: composer:v2
```

**Comment by it-spiderman** [comment]
@rht Thank you, after some more tinkering, all tests pass now

**Comment by it-spiderman** [comment]
Again, this should be squash merged, commit history is not clean

**Comment by rht** [comment]
@FantasticoFox squash and merge is not enabled for this repo.

**Comment by it-spiderman** [comment]
I tried, can be enabled (if it want)

**Comment by rht** [comment]
Oh, didn't know I had the privilege to enable it.

**Comment by it-spiderman** [comment]
Whohooo
Other steps (tagging and upgrading other repos) should be done soon, so it doesnt lead to mismatches in versions.
@FantasticoFox knows the details (by mail)

**Pull request merged**
