### PR TITLE
feat: Delete shorter pages on import collision

### PR DESCRIPTION
**Pull request by it-spiderman**

### CODE REVIEW

**Comment by FantasticoFox** [comment]
Testing failed. 

I created a page with multiple sub-resources / transclusions. I deleted the main page but not the transclusions. I imported the main page but failed due to existing transclusion pages. Expected behavior would be that the main page gets imported while the transcluded sub-pages are skipped as they exist (or "updated(removed and imported)" if the imported one has a longer history).

If an imported resource has sub-resources which are unchanged it should skip them. Currently with the consequence that the import procedure **is completely stopped** and the next resource is not being processed.
It is correct to return with an information message and say that this sub-resource was not important and therefore the import was skipped for that resource.

image

**Review by FantasticoFox — CHANGES_REQUESTED** [review]
Needs more work and resolution of the problem shown in the comments.

**Comment by it-spiderman** [comment]
This particular message is not a collision, its a fatal returned by the uploader. However, i will turn it into the collision, so that it gets displayed correctly

**Comment by it-spiderman** [comment]
Done, improved

**Comment by FantasticoFox** [comment]
Looks good now. Well done!

**Pull request merged**
